import studioRaw from '../assets/templates/studio-25.homeplanr?raw'
import oneBedroomRaw from '../assets/templates/one-bedroom-45.homeplanr?raw'

/**
 * Bundled starter plans (M6, 0.4.0) — ordinary current-version .homeplanr
 * documents generated by scripts/makeTemplates.ts and bundled via Vite ?raw
 * (identical dev/packaged, no fs-scope work). Regenerate at every schema
 * bump (RUNBOOK checklist) so they always parse with healed=false.
 */
export interface TemplatePlan {
  id: string
  /** Display name — becomes the new document's name. */
  name: string
  raw: string
}

export const TEMPLATES: readonly TemplatePlan[] = [
  { id: 'studio-25', name: 'Studio 25 m²', raw: studioRaw },
  { id: 'one-bedroom-45', name: '1-bedroom 45 m²', raw: oneBedroomRaw },
]
